-- =============================================================================
-- catalog-service — initial schema
--
-- Database and Java identifiers use the same English vocabulary. Flyway is the
-- schema authority; JPA validates these mappings at application startup.
--
-- Conventions applied throughout:
--   money      NUMERIC(10,2)  -> BigDecimal   (never a floating point type)
--   timestamps TIMESTAMPTZ    -> Instant      (a container in UTC and a laptop
--                                              in Africa/Casablanca must agree)
--   every foreign key is indexed — PostgreSQL does not do this for you

CREATE TABLE category
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  VARCHAR(32)  NOT NULL,
    label VARCHAR(128) NOT NULL,
    CONSTRAINT uq_category_code UNIQUE (code)
);

CREATE TABLE brand
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    CONSTRAINT uq_brand_name UNIQUE (name)
);

CREATE TABLE product
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference      VARCHAR(64)    NOT NULL,
    label          VARCHAR(255)   NOT NULL,
    description    TEXT,
    price_excl_vat NUMERIC(10, 2) NOT NULL,
    unit           VARCHAR(16)    NOT NULL,
    stock_quantity INTEGER        NOT NULL DEFAULT 0,
    active         BOOLEAN        NOT NULL DEFAULT TRUE,
    category_id    BIGINT         NOT NULL,
    brand_id       BIGINT         NOT NULL,
    version        BIGINT         NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT uq_product_reference UNIQUE (reference),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT fk_product_brand FOREIGN KEY (brand_id) REFERENCES brand (id),
    CONSTRAINT ck_product_price CHECK (price_excl_vat >= 0),
    CONSTRAINT ck_product_stock CHECK (stock_quantity >= 0),
    CONSTRAINT ck_product_unit CHECK (unit IN ('ITEM', 'METER', 'BOX'))
);

-- `version` backs JPA optimistic locking. The pessimistic lock taken during
-- reservation (ADR-0003) protects concurrent checkouts from each other; this
-- column catches an administrator editing a product while a reservation is in
-- flight.

CREATE INDEX idx_product_category ON product (category_id);
CREATE INDEX idx_product_brand ON product (brand_id);

-- Every customer-facing listing filters on active = TRUE, so inactive rows are
-- excluded from this partial index.
CREATE INDEX idx_product_active ON product (active) WHERE active;

-- Case-insensitive search over label and reference. pg_trgm gives
-- ILIKE '%term%' an index to use; without it every search is a sequential scan.
CREATE
EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_product_label_trgm ON product USING gin (label gin_trgm_ops);
CREATE INDEX idx_product_reference_trgm ON product USING gin (reference gin_trgm_ops);

-- --------------------------------------------------------------- reservation
-- ADR-0003. A reservation replaces a direct cross-service stock decrement,
-- which cannot be made atomic across two databases.
--
-- Available stock is product.stock_quantity - SUM(active, unexpired holds).
-- It is computed on read, never stored, so it cannot drift from the rows that
-- justify it.
CREATE TABLE reservation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_reference VARCHAR(64) NOT NULL,
    status          VARCHAR(16) NOT NULL,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- This unique constraint is the idempotency key. A retried reservation for
    -- the same order collides here instead of creating a second stock hold.
    CONSTRAINT uq_reservation_order_reference UNIQUE (order_reference),
    CONSTRAINT ck_reservation_status
        CHECK (status IN ('ACTIVE', 'CONFIRMED', 'RELEASED', 'EXPIRED', 'RESTOCKED'))
);

-- Drives the expiry sweep. Terminal reservations accumulate but are irrelevant
-- to this index.
CREATE INDEX idx_reservation_expiry
    ON reservation (expires_at) WHERE status = 'ACTIVE';

CREATE TABLE reservation_line
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT  NOT NULL,
    product_id     BIGINT  NOT NULL,
    quantity       INTEGER NOT NULL,

    CONSTRAINT fk_reservation_line_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE,
    CONSTRAINT fk_reservation_line_product
        FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT ck_reservation_line_quantity CHECK (quantity > 0),
    CONSTRAINT uq_reservation_line_product UNIQUE (reservation_id, product_id)
);

CREATE INDEX idx_reservation_line_reservation ON reservation_line (reservation_id);

-- The hot path of the availability query: how much of product X is held now?
CREATE INDEX idx_reservation_line_product ON reservation_line (product_id);
