/**
 * Inbound request DTOs, one per endpoint that accepts a body.
 *
 * <h2>Why these are records</h2>
 *
 * A request is a <em>value</em>: it has no identity, no lifecycle and no
 * behaviour beyond carrying data across the boundary. A record says exactly
 * that in the language rather than in an annotation processor — immutability,
 * component equality, {@code toString} and a canonical constructor, none of it
 * generated by anything the IDE has to be taught about.
 *
 * <p>Two properties earn their place here specifically:
 *
 * <ul>
 *   <li><b>The compact constructor is a validation choke point.</b> It runs on
 *       every construction path, Jackson's included, so a DTO that exists is a
 *       DTO whose invariants held. A class with setters can be validated and
 *       then mutated before it reaches the use case.</li>
 *   <li><b>Bean Validation still works.</b> Constraints on components propagate
 *       to the field, accessor and constructor parameter, so {@code @Valid
 *       @RequestBody} behaves as it does on a JavaBean — including cascading
 *       into nested records via {@code List<@Valid Line>}.</li>
 * </ul>
 *
 * <h2>Where a record would stop being the right answer</h2>
 *
 * <p><b>Partial updates.</b> A record cannot distinguish "field absent" from
 * "field explicitly null", because every component is always present. Today
 * this costs nothing: product updates are {@code PUT} (full replacement) and the
 * only {@code PATCH} carries a single required field. A genuine partial
 * {@code PATCH} would need {@code Optional}/{@code JsonNullable} components or
 * a class with presence flags — reach for that when the endpoint arrives, not
 * before.
 *
 * <p><b>Inheritance.</b> Records are final and extend nothing. Shared shape has
 * to come from composition or a sealed interface. That has not bitten yet and
 * mostly reads as a feature.
 *
 * <p>Note the contrast with {@code adapter.out.persistence.entity}, where the
 * classes are deliberately <em>not</em> records: JPA needs a no-arg constructor,
 * mutable fields for dirty checking, and identity-based equality. Same layer,
 * opposite answer, for reasons that have nothing to do with taste.
 */
package com.volt.order.infrastructure.adapter.in.web.dto.request;
