-- =============================================================================
-- order-service — initial schema
--
-- Database and Java identifiers use the same English vocabulary. This database
-- contains no product table by design: catalog owns products, and the only
-- product data here is the priced snapshot copied onto an order line at
-- checkout (ADR-0002).
-- =============================================================================

-- ----------------------------------------------------------------------- cart
-- One durable cart per customer. customer_id is the Keycloak `sub` claim, so
-- it is a UUID rather than a local numeric identifier.
CREATE TABLE cart (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_cart_customer UNIQUE (customer_id)
);

CREATE TABLE cart_line (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,

    CONSTRAINT fk_cart_line_cart
        FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE,
    CONSTRAINT ck_cart_line_quantity CHECK (quantity > 0),
    CONSTRAINT uq_cart_line_product UNIQUE (cart_id, product_id)
);

CREATE INDEX idx_cart_line_cart ON cart_line (cart_id);

-- A cart is an intention, not an agreement, so it stores no price or label.
-- Prices are rendered live from catalog and copied only at checkout.

-- --------------------------------------------------------------------- orders
-- A database sequence prevents concurrent checkouts from generating the same
-- human-readable order number after stock has already been reserved.
CREATE SEQUENCE order_number_seq START WITH 1 INCREMENT BY 1;

-- `order` is a SQL keyword, so the table uses the unquoted plural `orders`.
CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number         VARCHAR(32)    NOT NULL,
    customer_id    UUID           NOT NULL,
    status         VARCHAR(16)    NOT NULL,
    reservation_id BIGINT,
    total_excl_vat NUMERIC(12, 2) NOT NULL,
    vat_amount     NUMERIC(12, 2) NOT NULL,
    total_incl_vat NUMERIC(12, 2) NOT NULL,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT uq_orders_number UNIQUE (number),
    CONSTRAINT ck_orders_status
        CHECK (status IN ('CREATED', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_totals
        CHECK (total_excl_vat >= 0 AND vat_amount >= 0 AND total_incl_vat >= 0)
);

-- Lists a customer's orders newest first.
CREATE INDEX idx_orders_customer ON orders (customer_id, created_at DESC);

-- Finds orders whose reservation was released by the expiry sweep.
CREATE INDEX idx_orders_reservation
    ON orders (reservation_id) WHERE reservation_id IS NOT NULL;

-- ---------------------------------------------------------------- order_line
-- Product reference, label, and price are immutable checkout snapshots. There
-- is deliberately no foreign key on product_id because that row belongs to
-- another service's database.
CREATE TABLE order_line (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT         NOT NULL,
    product_id          BIGINT         NOT NULL,
    product_reference   VARCHAR(64)    NOT NULL,
    product_label       VARCHAR(255)   NOT NULL,
    unit_price_excl_vat NUMERIC(10, 2) NOT NULL,
    quantity            INTEGER        NOT NULL,
    line_total_excl_vat NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_order_line_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT ck_order_line_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_line_price CHECK (unit_price_excl_vat >= 0)
);

CREATE INDEX idx_order_line_order ON order_line (order_id);
